WIP - First pass reviewing for `RemoveResource()`
Juniper/terraform-provider-apstra pull request #117
Opened 2023-05-26 20:04 UTC by chrismarget-j

#83 was concerned with cases where we failed to invoke `resp.State.RemoveResource()`.

It turns out that `Read()` is the only method where that call makes sense:
- `Create()`'s job is to make the resource, so you wouldn't use it here.
- `Read()` might discover the resource missing. That's when it makes sense.
- `Update()` expects the plan to be possible to execute. Per [this comment](https://discuss.hashicorp.com/t/when-the-api-doesnt-recognize-the-object-id-during-update/53218/6) terraform will ignore attempts to remove state anyway.
- `Delete()` used to require invoking `RemoveResource()` but hasn't required it for several versions now.

After first writing up #83 I probably over-rotated on this issue, started calling `RemoveResource()` in places where it didn't make sense.

2023-05-30 23:37 UTC, rajagopalans requested changes
Minor phrase modifications.
Otherwise looks good.

2023-05-30 23:37 UTC, rajagopalans commented on apstra/resource_datacenter_routing_zone.go
> +		resp.Diagnostics.AddError("error creating client for Apstra Blueprint", err.Error())
Do we need to say "Apstra" Blueprint? Maybe "Datacenter" Blueprint to distinguish from later bps?

2023-05-30 23:37 UTC, rajagopalans commented on apstra/resource_datacenter_routing_zone.go
> +		resp.Diagnostics.AddError("error creating blueprint client", err.Error())
Maybe use the same phrase as in line 205?

2023-05-30 23:37 UTC, rajagopalans commented on apstra/resource_datacenter_virtual_network.go
> +		resp.Diagnostics.AddError("error creating blueprint client", err.Error())
Same as previous comment atbout error creating blueprint client

2023-05-30 23:37 UTC, rajagopalans commented on apstra/resource_datacenter_virtual_network.go
> +		resp.Diagnostics.AddError("error creating blueprint client", err.Error())
same comment as before for phrase

2023-05-30 23:56 UTC, chrismarget-j commented on apstra/resource_datacenter_blueprint.go
> +			fmt.Sprintf("fetching blueprint %q", state.Id.ValueString()),
The word "error" already appears in red text. The text we add as a summary is in white.

Best case, the error is something like "thing not found", in which case we get an error like:

```
| terraform encountered an error: thing not found
| stuff
| detailed error goes here
```

I don't remember the specific text, but I made this change because I saw the word "error" twice, back-to-back. Once from the diagnostic boilerplate and once from the summary text: "error error fetching blueprint" ... or something like that.

In this case we can't give an error summary (not found), the best we can do is say what we were doing.

It's worth brainstorming about because I'm not super happy with this solution either. But it was a deliberate call.

2023-05-31 00:46 UTC, chrismarget-j commented on apstra/resource_datacenter_virtual_network.go
> +		resp.Diagnostics.AddError("error creating blueprint client", err.Error())
3ebafeb

2023-05-31 00:46 UTC, chrismarget-j commented on apstra/resource_datacenter_routing_zone.go
> +		resp.Diagnostics.AddError("error creating client for Apstra Blueprint", err.Error())
3ebafeb

2023-05-31 00:46 UTC, chrismarget-j commented on apstra/resource_datacenter_routing_zone.go
> +		resp.Diagnostics.AddError("error creating blueprint client", err.Error())
3ebafeb

2023-05-31 00:47 UTC, chrismarget-j commented on apstra/resource_datacenter_virtual_network.go
> +		resp.Diagnostics.AddError("error creating blueprint client", err.Error())
3ebafeb

2023-05-31 00:48 UTC, chrismarget-j commented
I introduced a constant to normalize the willy-nilly phrasing of the "failed to create a blueprint client" condition:

```go
ErrDCBlueprintCreate = "Failed to create client for Datacenter Blueprint %s"
```

2023-05-31 02:33 UTC, rajagopalans approved these changes

2023-05-31 02:39 UTC, merged