Datasource datacenter property sets
Juniper/terraform-provider-apstra pull request #135
Opened 2023-06-12 05:41 UTC by rajagopalans

This PR takes care of importing property sets into blueprints.

2023-06-12 13:11 UTC, chrismarget-j requested changes
Also, see teams comment about the "sets" data source.

2023-06-12 13:11 UTC, chrismarget-j commented on apstra/resource_datacenter_property_set.go
> +	bpClient, err := o.client.NewTwoStageL3ClosClient(ctx, apstra.ObjectId(state.BlueprintId.ValueString()))
needs err handling which detects 404 and exits gracefully.

2023-06-12 16:25 UTC, rajagopalans commented on apstra/data_source_datacenter_property_set.go
> +		MarkdownDescription: "This data source provides details of a specific PropertySet imported into a blueprint.\n\n" +
Done

2023-06-12 16:50 UTC, rajagopalans commented on apstra/data_source_datacenter_property_set.go
> +	bpClient, err := o.client.NewTwoStageL3ClosClient(ctx, apstra.ObjectId(config.BlueprintId.ValueString()))
Done

2023-06-12 16:52 UTC, rajagopalans commented on apstra/blueprint/datacenter_property_set.go
> +func (o *DatacenterPropertySet) LoadApiData(ctx context.Context, in *apstra.TwoStageL3ClosPropertySet, loadkeys bool, diags *diag.Diagnostics) {
Done

2023-06-12 17:32 UTC, rajagopalans commented on apstra/blueprint/datacenter_property_set.go
> +			MarkdownDescription: "This is true if the Property Set does not match the global property set",
>Maybe something closer to "stale flag, as set by apstra"?
that is even more vague :-)
I thought showing what it means in practical sense will prevent the terraform user from having to dig through the Apstra API

2023-06-12 21:25 UTC, rajagopalans commented on apstra/resource_datacenter_property_set.go
> +	bpClient, err := o.client.NewTwoStageL3ClosClient(ctx, apstra.ObjectId(state.BlueprintId.ValueString()))
done

2023-06-12 21:26 UTC, rajagopalans commented on apstra/resource_datacenter_property_set.go
> +	state.LoadApiData(ctx, api, false, &resp.Diagnostics)
Done

2023-06-13 13:59 UTC, rajagopalans commented on apstra/resource_datacenter_property_set.go
> +	if err != nil && errors.As(err, &ace) && ace.Type() == apstra.ErrNotfound {
Done

2023-06-13 14:00 UTC, rajagopalans commented on apstra/resource_datacenter_property_set.go
> +	// set state
Done, covered by previous comment

2023-06-13 15:17 UTC, chrismarget-j commented on apstra/data_source_datacenter_property_set.go
> +		MarkdownDescription: "This data source provides details of a specific PropertySet imported into a blueprint.\n\n" +
Please make the same change in other `MarkdownDescription` strings in this file?

2023-06-13 15:28 UTC, chrismarget-j commented on apstra/data_source_datacenter_property_set.go
> +	bpClient, err := o.client.NewTwoStageL3ClosClient(ctx, apstra.ObjectId(config.BlueprintId.ValueString()))
Please use the pattern from
[apstra/data_source_datacenter_routing_zone.go](https://github.com/Juniper/terraform-provider-apstra/blob/bdf1341538cd2bf805df65fcb8c238edfedadb25/apstra/data_source_datacenter_routing_zone.go#LL47C23-L47C23) for more graceful handling of 404.

Also, comment seems to be stray copy pasta.

2023-06-13 15:28 UTC, rajagopalans commented on apstra/data_source_datacenter_property_set.go
> +		MarkdownDescription: "This data source provides details of a specific PropertySet imported into a blueprint.\n\n" +
I think I got all.
I have another question/request for guidance.
Should I call them "Datacenter Property Set" in error statements  or "Imported Property Sets"? I just noticed that I that errors say "DatacenterPropertySet". 
a "DatacenterPropertySet" is what it's called in Terraform, which is appropriate for errors raising from TF. 
Imported property sets are what they are. 
eg. 
				"DatacenterPropertySet not found",
				fmt.Sprintf("DatacenterPropertySet with label %q not found", config.Label.ValueString()))
Should that say "imported Property Set not found"

2023-06-13 15:37 UTC, chrismarget-j commented on apstra/resource_datacenter_property_set.go
> +	bpClient, err := o.client.NewTwoStageL3ClosClient(ctx, apstra.ObjectId(plan.BlueprintId.ValueString()))
need to handle `err`

2023-06-13 15:41 UTC, rajagopalans commented on apstra/data_source_datacenter_property_set.go
> +		MarkdownDescription: "This data source provides details of a specific PropertySet imported into a blueprint.\n\n" +
Resolved per team meeting.
Error messages will stay as is

2023-06-13 15:47 UTC, chrismarget-j commented on apstra/blueprint/datacenter_property_set.go
> +func (o *DatacenterPropertySet) LoadApiData(ctx context.Context, in *apstra.TwoStageL3ClosPropertySet, loadkeys bool, diags *diag.Diagnostics) {
Please make `d` into `diags`? My brain needs the consistency on these kind of things.

2023-06-13 15:49 UTC, chrismarget-j commented on apstra/data_source_datacenter_property_set.go
> +	state.Id = types.StringValue(string(api.Id))
need to eliminate the `state.Id` assignment.

2023-06-13 16:01 UTC, chrismarget-j commented on apstra/blueprint/datacenter_property_set.go
> +			MarkdownDescription: "Subset of Keys to import. Empty set implies all keys imported.",
Validation doesn't permit "empty set" - perhaps this should say "Omit this field to import all keys"

2023-06-13 16:12 UTC, chrismarget-j commented on apstra/resource_datacenter_property_set.go
> +	if err != nil && errors.As(err, &ace) && ace.Type() == apstra.ErrNotfound {
I don't think this one needs special 404 handling, though I had some other ideas about this in the past (see previous PR about auditing `State.RemoveResource()`).

A 404 only happens here when the object is removed between the `plan` and `apply` steps. While we usually use "apply" which does both steps more or less back-to-back, some shops will generate a `plan`, save it, submit to a review process, and then execute the plan later.

The temporal window to lose (win?) this race condition can be pretty wide, but we know the object existed recently (when the plan was created).

So, broadly speaking, there's 3 different 404 handling scenarios:

1. resource `Read()` or `Delete()` 404's for the object or once of its parents -> this is a big surprise, we handle gracefully with `RemoveResource()`
2. data source `Read()` or resource `Create()` 404s -> less of a surprise (we had no evidence the required object actually exists), we should print a friendly error rather than dumping the API garbage.
3. resource `Update()` 404s -> in this case we knew the thing existed during plan, so it's a pretty big surprise and we can't handle it gracefully. Blowing up with an API error is more acceptable here.

2023-06-23 21:15 UTC, chrismarget-j approved these changes

2023-06-23 21:35 UTC, merged