Bug/174: improve error handling in `apstra_configlet` resource
Juniper/terraform-provider-apstra pull request #175
Opened 2023-07-06 15:47 UTC by chrismarget-j

- improve 404 handling
- whitespace/comments/readability

2023-07-06 22:22 UTC, rajagopalans requested changes

2023-07-06 22:22 UTC, rajagopalans commented on apstra/resource_configlet.go
> -		var ace apstra.ApstraClientErr
IIRC, when I was writing this, this step (remove the resource if you get a 404 on an update) was recommended. If the resource goes away, we do want to adjust the state accordingly right?

2023-07-06 22:22 UTC, rajagopalans commented on apstra/resource_configlet.go
> +	api, err := o.client.GetConfiglet(ctx, apstra.ObjectId(state.Id.ValueString()))
I am fine with this, but am curious if you triggered this condition (where it was an error on GET and it was not a 404).

2023-07-06 22:29 UTC, chrismarget-j commented on apstra/resource_configlet.go
> -		var ace apstra.ApstraClientErr
Apparently you can't `RemoveResource()` in `Update()`:

[From here:](https://discuss.hashicorp.com/t/when-the-api-doesnt-recognize-the-object-id-during-update/53218/6)

> You do not need to remove state along with an error, terraform will assume this is a mistake and keep the last state just in case.

I've been pulling these out since I learned about that behavior.

2023-07-06 22:32 UTC, chrismarget-j commented on apstra/resource_configlet.go
> +	api, err := o.client.GetConfiglet(ctx, apstra.ObjectId(state.Id.ValueString()))
I didn't bump into it. It's just something I noticed.

Other errors (especially timeout/unreachable) could happen here. If we don't bail out with an error the program will crash when `api` (value: `nil`) is dereferenced.

2023-07-10 14:01 UTC, rajagopalans approved these changes

2023-07-10 16:19 UTC, merged