Fixed issue # 98 - made sure any comments are < 76 chars
Juniper/terraform-provider-apstra pull request #220
Opened 2023-07-24 17:24 UTC by bwJuniper

2023-07-25 08:09 UTC, rajagopalans requested changes

2023-07-25 14:10 UTC, chrismarget-j commented on docs/data-sources/agents.md
> +# in with management IP addresses in the 192.168.100.0/24 subnet.
lol. the formatting's great, but the sentence never made any sense in the first place.

2023-07-25 15:47 UTC, bwJuniper commented on docs/data-sources/agents.md
> +# in with management IP addresses in the 192.168.100.0/24 subnet.
ok i fixed it by removing the in

2023-07-25 15:48 UTC, chrismarget-j commented on docs/data-sources/agents.md
> +# in with management IP addresses in the 192.168.100.0/24 subnet.
lgtm

2023-07-25 15:49 UTC, chrismarget-j approved these changes

2023-07-26 15:25 UTC, rajagopalans approved these changes

2023-07-26 15:27 UTC, merged