fix the string validator for rack names
Juniper/terraform-provider-apstra pull request #284
Opened 2023-08-14 03:10 UTC by rajagopalans

I discovered this limit while writing configs for the AI racks.

2023-08-14 11:25 UTC, chrismarget-j submitted a review, later dismissed

2023-08-17 22:15 UTC, chrismarget-j requested changes
I think that "between" might need to be 0-18.

Warrants an experiment at least.

2023-08-18 18:05 UTC, rajagopalans commented
> I think that "between" might need to be 0-18.
> 
> Warrants an experiment at least.

│ Error: Invalid Attribute Value Length
│ 
│   with apstra_rack_type.AI_16xA100,
│   on racks.tf line 30, in resource "apstra_rack_type" "AI_16xA100":
│   30:   name                       = "012345678901234567"
│ 
│ Attribute name string length must be between 1 and 17, got: 18

Admittedly confusing, but works :-)

2023-08-18 20:04 UTC, chrismarget-j approved these changes
It must have been the Go doc comment which led me to believe 0-18 was the appropriate value.

Upstream PR:
https://github.com/hashicorp/terraform-plugin-framework-validators/pull/157

And we now have #304

2023-08-18 20:53 UTC, merged