Introduce `apstra_modular_device_profile` resource
Juniper/terraform-provider-apstra pull request #393
Opened 2023-10-06 03:27 UTC by chrismarget-j

2023-10-06 12:55 UTC, rajagopalans requested changes

2023-10-06 12:55 UTC, rajagopalans commented on apstra/resource_modular_device_profile.go
> +				"Slot Numbers must be positive numbers",
Error should probably mention the range (looks to be 10-64), not just positive ints

2023-10-06 21:11 UTC, chrismarget-j commented on apstra/resource_modular_device_profile.go
> +				"Slot Numbers must be positive numbers",
Range? I'm not following.

I briefly considered using a `uint8` for the slot number (does any chassis have more than 255 slots?), but decided it would be safer/easier to allow silly big numbers.

Anyway, 0 is a positive integer, right?

2023-10-08 04:02 UTC, rajagopalans commented on apstra/resource_modular_device_profile.go
> +				"Slot Numbers must be positive numbers",
I misunderstood the Parseint statement.

2023-10-08 04:03 UTC, rajagopalans approved these changes

2023-10-08 13:49 UTC, merged