audit-resource-blueprint-id for requires-replace
Juniper/terraform-provider-apstra pull request #414
Opened 2023-10-24 16:40 UTC by bwJuniper

Reviewed all resources with datacenter or blueprint that would need required_replace on the id.
Fixes #408 
added planmodifier for connectivity_template.go and updated README.md to add some jazz

2023-10-24 20:40 UTC, rajagopalans requested changes
I think that most if not all resources that have blueprint_id will need to be replaced if the blueprint id is changed

2023-10-25 00:43 UTC, chrismarget-j approved these changes

2023-10-25 00:45 UTC, chrismarget-j commented
> I think that most if not all resources that have blueprint_id will need to be replaced if the blueprint id is changed

The one Bill found (in this PR) might be the only problem in this regard.

2023-10-25 10:56 UTC, rajagopalans commented
> > I think that most if not all resources that have blueprint_id will need to be replaced if the blueprint id is changed
> 
> The one Bill found (in this PR) might be the only problem in this regard.
Oh cool, looks like we already got the other resources. For some reason I thought we hadn't done any of them.

2023-10-25 10:57 UTC, rajagopalans approved these changes

2023-10-25 16:15 UTC, merged