property set data and resource providers
Juniper/terraform-provider-apstra pull request #64
Opened 2023-05-04 17:14 UTC by rajagopalans

No tests yet.

2023-05-04 18:50 UTC, chrismarget-j approved these changes

2023-05-05 01:25 UTC, chrismarget-j requested changes
inline comments scattered around.

Also, need docs generated before the release process can run.

2023-05-05 01:25 UTC, chrismarget-j commented on apstra/resource_property_set.go
> +		return
This should just invoke `resp.State.RemoveResource()`, no need for an error.

2023-05-05 01:25 UTC, chrismarget-j commented on apstra/apstra_validator/parse_json.go
> +}
`ParseJsonValidatorRequest` and `ParseJsonValidatorResponse` aren't used, can be deleted.

2023-05-05 01:25 UTC, chrismarget-j commented on apstra/design/property_set.go
> +			MarkdownDescription: "Populate this field to look up a property set by name. Required when `id` is omitted.",
Please make these comments consistent with capitalization. Apstra objects in these doc strings are capitalized: "Property Set"

Several instances in this file.

2023-05-05 01:25 UTC, chrismarget-j commented on apstra/design/property_set.go
> +func (o *PropertySet) Request(ctx context.Context, diags *diag.Diagnostics) *apstra.PropertySetData {
`ctx` and `diags` aren't used. I'd like to keep them for consistency with the other `Request()` methods, but they can be reduced to `_` when unused.

2023-05-05 01:25 UTC, chrismarget-j commented on apstra/utils/compare_jsons.go
> +
Extraneous blank line breaks GoDoc notation.

2023-05-05 04:32 UTC, rajagopalans commented on apstra/resource_property_set.go
> +		return
done

2023-05-05 04:32 UTC, rajagopalans commented on apstra/apstra_validator/parse_json.go
> +}
done

2023-05-05 04:35 UTC, rajagopalans commented on apstra/design/property_set.go
> +			MarkdownDescription: "Populate this field to look up a property set by name. Required when `id` is omitted.",
Done

2023-05-05 04:36 UTC, rajagopalans commented on apstra/design/property_set.go
> +func (o *PropertySet) Request(ctx context.Context, diags *diag.Diagnostics) *apstra.PropertySetData {
Done

2023-05-05 11:21 UTC, chrismarget-j commented on apstra/design/property_set.go
> +func (o *PropertySet) Request(ctx context.Context, diags *diag.Diagnostics) *apstra.PropertySetData {
missing commit? They're still named `ctx` and `diags` here.

2023-05-05 12:42 UTC, rajagopalans commented
No idea why. No pending commits and local copy has _

On Fri, May 5, 2023, 7:22 AM chrismarget-j ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In apstra/design/property_set.go
> <https://github.com/Juniper/terraform-provider-apstra/pull/64#discussion_r1185977999>
> :
>
> > +			MarkdownDescription: "Set of blueprints that this property set might be associated with.",
> +			Computed:            true,
> +			ElementType:         types.StringType,
> +		},
> +	}
> +}
> +
> +func (o *PropertySet) LoadApiData(ctx context.Context, in *apstra.PropertySetData, diags *diag.Diagnostics) {
> +	o.Label = types.StringValue(in.Label)
> +	var d diag.Diagnostics
> +	o.Blueprints, d = types.SetValueFrom(ctx, types.StringType, in.Blueprints)
> +	diags.Append(d...)
> +	o.Values = types.StringValue(string(in.Values))
> +}
> +
> +func (o *PropertySet) Request(ctx context.Context, diags *diag.Diagnostics) *apstra.PropertySetData {
>
> missing commit? They're still named ctx and diags here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Juniper/terraform-provider-apstra/pull/64#discussion_r1185977999>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARW4W4SXXYIEA3GTTOYLMLXETPF7ANCNFSM6AAAAAAXWCAHPU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-05 12:47 UTC, chrismarget-j commented on apstra/design/property_set.go
> +func (o *PropertySet) Request(ctx context.Context, diags *diag.Diagnostics) *apstra.PropertySetData {
looks okay to me now. Git pull just collected:
```
   7330bc7..0dc6c0e  propertysets -> origin/propertysets
```

Weird. I don't know why I saw this in the web view.

2023-05-05 20:58 UTC, rajagopalans commented on apstra/utils/compare_jsons.go
> +
fixed

2023-05-05 21:05 UTC, chrismarget-j approved these changes

2023-05-05 21:08 UTC, merged