add the code and test for the telemetry service registry entry providers
Juniper/terraform-provider-apstra pull request #706
Opened 2024-07-11 07:47 UTC by rajagopalans

2024-07-11 18:35 UTC, chrismarget-j requested changes

2024-07-11 18:35 UTC, chrismarget-j commented on apstra/analytics/telemetry_service_registry_entry.go
> +			PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
Does this plan modifier make sense? I don't think a `Required` attribute can ever be "unknown".

2024-07-11 18:35 UTC, chrismarget-j commented on apstra/analytics/telemetry_service_registry_entry.go
> +			},
"version" doesn't seem to be a field which can be accessed via the Web UI. Should we be allowing the user to control it via terraform?

2024-07-11 18:35 UTC, chrismarget-j commented on apstra/analytics/telemetry_service_registry_entry.go
> +	ApplicationSchema types.String `tfsdk:"application_schema"`
Should this be a `jsontypes.Normalized`?

2024-07-11 18:35 UTC, chrismarget-j commented on apstra/analytics/telemetry_service_registry_entry.go
> +func (o *TelemetryServiceRegistryEntry) Request(ctx context.Context, d *diag.Diagnostics) *apstra.TelemetryServiceRegistryEntry {
Please `_` the unused `context.Context`

2024-07-11 18:35 UTC, chrismarget-j commented on apstra/data_source_telemetry_service_registry_entries.go
> +				MarkdownDescription: "A set of Apstra object ID numbers.",
Should this say "service names"?

2024-07-11 18:35 UTC, chrismarget-j commented on apstra/data_source_telemetry_service_registry_entries.go
> +	var err error
err redeclared on next line. delete.

2024-07-11 18:35 UTC, chrismarget-j commented on apstra/data_source_telemetry_service_registry_entries.go
> +		resp.Diagnostics.AddError("error retrieving Property Set IDs", err.Error())
s/Property Set/Service Entries/

2024-07-11 18:35 UTC, chrismarget-j commented on apstra/data_source_telemetry_service_registry_entry.go
> +			"At least one optional attribute is required.",
MarkdownDescription is for humans. Please put spaces in TelemetryServiceRegistryEntry.

Also, no attributes are optional here.

2024-07-11 18:35 UTC, chrismarget-j commented on apstra/data_source_telemetry_service_registry_entry.go
> +	api, err = o.client.GetTelemetryServiceRegistryEntry(ctx, config.ServiceName.ValueString())
Use walrus operator rather than var declarations here. Declarations only required in other data sources because of `switch` on optional attributes.

2024-07-11 18:35 UTC, chrismarget-j commented on apstra/resource_telemetry_service_registry_entry.go
> +		MarkdownDescription: docCategoryDesign + "This resource creates a Property Set in the Apstra Design tab.",
Property Set

2024-07-11 18:35 UTC, chrismarget-j commented on apstra/resource_telemetry_service_registry_entry.go
> +	tsRequest := plan.Request(ctx, &resp.Diagnostics)
Need to check for error

2024-07-11 18:35 UTC, chrismarget-j commented on apstra/resource_telemetry_service_registry_entry.go
> +	var api *apstra.TelemetryServiceRegistryEntry
Use walrus operator rather than declarations

2024-07-11 18:35 UTC, chrismarget-j commented on examples/data-sources/apstra_telemetry_service_registry_entries/example.tf
> +#all_entries = {
prettify this or delete it. It's not readable.

2024-07-11 18:35 UTC, chrismarget-j commented on examples/resources/apstra_telemetry_service_registry_entry/example.tf
> +		{
Please use the HCL formatter for this. spaces not tabs, etc...

2024-07-12 00:57 UTC, rajagopalans commented on apstra/analytics/telemetry_service_registry_entry.go
> +			PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
No. Dropped.

2024-07-12 01:03 UTC, rajagopalans commented on apstra/analytics/telemetry_service_registry_entry.go
> +			},
The API seems to permit viewing and changing it.
I have changed it to Computed for now.

2024-07-12 01:04 UTC, rajagopalans commented on apstra/analytics/telemetry_service_registry_entry.go
> +func (o *TelemetryServiceRegistryEntry) Request(ctx context.Context, d *diag.Diagnostics) *apstra.TelemetryServiceRegistryEntry {
Done

2024-07-12 01:05 UTC, rajagopalans commented on apstra/data_source_telemetry_service_registry_entries.go
> +				MarkdownDescription: "A set of Apstra object ID numbers.",
Fixed

2024-07-12 01:06 UTC, chrismarget-j commented on apstra/analytics/telemetry_service_registry_entry.go
> +			},
I played around with this attribute in the REST API Explorer a bit ... and broke the GUI. White screen. <shrug>

2024-07-12 01:07 UTC, rajagopalans commented on apstra/resource_telemetry_service_registry_entry.go
> +	tsRequest := plan.Request(ctx, &resp.Diagnostics)
Done

2024-07-12 11:09 UTC, rajagopalans commented on apstra/resource_telemetry_service_registry_entry.go
> +	var api *apstra.TelemetryServiceRegistryEntry
Done

2024-07-12 14:13 UTC, rajagopalans commented on apstra/analytics/telemetry_service_registry_entry.go
> +	ApplicationSchema types.String `tfsdk:"application_schema"`
Fixed

2024-07-12 14:21 UTC, rajagopalans commented on examples/data-sources/apstra_telemetry_service_registry_entries/example.tf
> +#all_entries = {
Fixed

2024-07-12 14:58 UTC, rajagopalans commented on examples/resources/apstra_telemetry_service_registry_entry/example.tf
> +		{
Done

2024-07-13 01:18 UTC, chrismarget-j approved these changes

2024-07-13 01:35 UTC, merged