Data source property set test
Juniper/terraform-provider-apstra pull request #74
Opened 2023-05-09 19:15 UTC by rajagopalans

2023-05-10 14:11 UTC, chrismarget-j requested changes

2023-05-10 14:11 UTC, chrismarget-j commented on apstra/data_source_property_set_test.go
> +	dataSourcePropertuSetTemplateByNameHCL = `
"propertu"

2023-05-10 14:11 UTC, chrismarget-j commented on apstra/test_utils/property_set.go
> +func PropertySetTest(ctx context.Context) (*apstra.PropertySet, func(context.Context) error, error) {
Please name this `PropertySetA()` for consistency with similar functions. "test" is already in the package name and "A" to prepare for the possibility that we need a different property set in future tests.

2023-05-10 14:11 UTC, chrismarget-j commented on apstra/test_utils/property_set.go
> +		return nil, nil, err
This should return a usable function as the 2nd argument, even a no-op one so that the caller doesn't have to worry about nil pointer dereference. `TestAccDataSourcePropertySet()` will try to run this without checking for `nil`.

I may have used this pattern with `nil` before, but have since decided it's easier to return a `safe` no-op function that make it the caller's problem to worry about.

If you notice it somewhere else, please open an issue.

same problem on line 23 and 27.

2023-05-10 19:20 UTC, rajagopalans commented on apstra/data_source_property_set_test.go
> +	dataSourcePropertuSetTemplateByNameHCL = `
Fixed to Propertah per Eric Cartman :-)

2023-05-10 19:38 UTC, rajagopalans commented on apstra/test_utils/property_set.go
> +		return nil, nil, err
I saw it for IPV4 pool.
I fixed it there as well and added it to the PR

2023-05-10 19:46 UTC, rajagopalans commented on apstra/test_utils/property_set.go
> +func PropertySetTest(ctx context.Context) (*apstra.PropertySet, func(context.Context) error, error) {
Fixed

2023-05-11 15:20 UTC, chrismarget-j approved these changes

2023-05-11 15:32 UTC, merged